#!/bin/bash

# Inject NVIDIA variables to bypass Proton boundaries
export __NV_PRIME_RENDER_OFFLOAD=1
export __VK_LAYER_NV_optimus=NVIDIA_only
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json

# Set NVIDIA Performance Level 2
sudo nvidia-smi -lgc 210,1600
sudo nvidia-smi -lmc 810,6001

# Execute script when a game launches
"$@"

# Reset NVIDIA Performance Level when closing the game
sudo nvidia-smi -rgc
sudo nvidia-smi -rmc